title: Luis Guerrero
description: Engineering Manager | Data Platforms & Infrastructure
theme: jekyll-theme-minimal   # other good choices: jekyll-theme-cayman, slate, minima
logo: /assets/profile.jpg     # optional, add an image later
